#12 -portofolio: portofolio projects section
nraufu/portofolio pull request #3
Opened 2020-07-20 09:53 UTC by nraufu

> #### What does this PR do?
- add the portfolio section listing all projects I worked on 
> #### Description of Task to be completed
- add the name of the project
- add a thumbnail of the project
- add the description of the project besides the thumbnail
> #### How should this be manually tested?
- git clone the application URL(`https://github.com/nraufu/portofolio.git`)
- open the `UI` folder
- open the index.html file in your brwoser
> #### What are the relevant trello stories?
 - 12
> #### Screenshots (if appropriate)
![portofolio](https://user-images.githubusercontent.com/49249449/87924349-12020100-ca7f-11ea-9b29-33051bc55a8e.PNG)

2020-07-20 09:56 UTC, nraufu commented
![](https://github.trello.services/images/mini-trello-icon.png) [portofolio page](https://trello.com/c/w1DJSRH7/12-portofolio-page)

2020-07-20 18:05 UTC, denislohan commented
@nraufu Nice work really.I have more task on this
1. can you add more works done. so that I can scroll left and right through your projects. lets say up to 5 projects. you can make up a fake project and add it there.

2020-07-20 18:06 UTC, istafrica-dennw requested changes

2020-07-20 18:06 UTC, denislohan commented on UI/index.html
> +            <div class="Portofolio__project">
You can add more projects. up to five. ,make sure they are scrollable horizontally nor vertically

2020-07-22 14:17 UTC, istafrica-dennw approved these changes

2020-07-22 14:17 UTC, merged